### ISSUE TITLE
Typescript import/usage

### ISSUE THREAD

**Issue by nigeon** [dydxprotocol/solo#260]
Hi!

I'm having problems importing the library in Typescript.
First of I did a `npm i -s @dydxprotocol/solo` and just trying to import it with `import { Solo } from "@dydxprotocol/solo";` When running I'm getting an error
```TSError: ⨯ Unable to compile TypeScript:
src/managers/dydx.ts:1:10 - error TS2305: Module '"./node_modules/@dydxprotocol/solo/dist/types/src/types"' has no exported member 'Solo'.

1 import { Solo } from "@dydxprotocol/solo";

```

Any idea why I can't import?

**Comment by AntonioJuliano** [comment]
Thanks for the report @nigeon! Can you please let us know which version of `@dydxprotocol/solo` you have installed?

**Comment by nigeon** [comment]
Hi!,

Currently it's "version": "0.6.1".
Typescript v. 3.4.5.
Nodejs v10.13.0

**Comment by nigeon** [comment]
Importing directly from src/Solo.ts file works, but that's not the way it should be.

`import { Solo } from "@dydxprotocol/solo/src/Solo";`
