### ISSUE TITLE
Liquidator Proxy Should Return Immediately If Not Liquidatable [3]

### ISSUE THREAD

**Issue by AntonioJuliano** [dydxprotocol/solo#284]
The liquidator proxy should not use much gas if the account is already liquidated or if the liquidating account is already at/under the min collateralization

**Comment by BrendanChou** [comment]
After review, it reverts if the Liquidation account has zero borrow or zero supply or is not liquidatable.

It does not immediately return if the liquidating account is under the min-collateralization, but it does revert (and does not call operate) so it would be caught in an estimate-gas call and does not use much gas on-chain
