### ISSUE TITLE
Optimize Interest Rate Functions

### ISSUE THREAD

**Issue by AntonioJuliano** [dydxprotocol/solo#326]
Optimize the interest rate functions to push for higher utilization. Consider making an updated interest rate setter contract if necessary

**Comment by ameenpv** [comment]
**Referring**: contracts/protocol/lib/Interest.sol

Line Numbers _87_ and _88_

Just making a suggestion. How about:
```
uint256 currentTime = Time.currentTime();
uint256 borrowInterest = rate.value.mul(currentTime.sub(index.lastUpdate));
```

For more: Péter Szilágyi's [answer from StackExchange](https://ethereum.stackexchange.com/a/3071)
