### ISSUE TITLE
Deposit operation not working with non-ETH assets

### ISSUE THREAD

**Issue by smogili1** [dydxprotocol/solo#345]
Hi - 

I am getting the following error in console from Metamask when executing a deposit operation using the code that's in the docs:

"gas required exceeds allowance (9962893) or always failing transaction"

Code used:

```
const result = await solo.standardActions.deposit({
  accountOwner: '0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5', // Your address
  marketId: MarketId.DAI,

   // Base units of the token, so 1e18 = 1 ETH
   // NOTE: USDC has 6 decimal places, so 1e6 = 1 USDC
  amount: new BigNumber('1e18'),
});
```

Also tried the operation directly as well :

```
operation.deposit({
            primaryAccountOwner: metamask.result.coinbase,
            primaryAccountId: new BigNumber(0),
            marketId: MarketId[tokenName],
            amount: {
              value: new BigNumber(value),
              reference: AmountReference.Delta,
              denomination: AmountDenomination.Actual,
            },
            from: metamask.result.coinbase,
          });
          operation.commit({
              from: metamask.result.coinbase,
              gasPrice: '1000000000',
              confirmationType: ConfirmationType.Confirmed,
            }).then(res => {
              console.log(res);
            }).catch(error => {
              console.log(error.transactionData.data)
          });
```

At a loss as to what's wrong or if there is a bug in solo code. Please help.

**Comment by BrendanChou** [comment]
Have you set ERC20 allowance on the contract?

**Comment by smogili1** [comment]
Yes, the ERC20 allowance has been set. Moreover, that shouldn't cause this error as in that case the transaction will fail after its executed not before.

**Comment by BrendanChou** [comment]
Is there enough DAI in the address that you're trying to submit from?

**Comment by BrendanChou** [comment]
I don't understand the part "the transaction will fail after its executed not before". It looks like it's failing before sending due to an error in the gas estimation

**Comment by smogili1** [comment]
why would gas estimation fail if there is no DAI balance or if allowance has not been set ? 

The transaction should fail after its executed in those cases.

**Comment by smogili1** [comment]
Thanks for helping with this, the issue in my case was that there was no DAI balance. 

My point was that the availability of DAI or whether the allowance is set should not impact the gas limit calculation. The transaction should go through but there should be an error event generated as part of the transaction. Unless there is some other logic, I am not sure why the gas limits are so high because balance was low. Its not an issue but my experience with other protocols has not been the same, so curious.

**Comment by BrendanChou** [comment]
To calculate the gas needed, the node runs the transaction through the VM. So if the DAI is untransferrable (insufficient balance) then the transaction will fail and it doesn't know what to estimate for the gas
