### ISSUE TITLE
Accounts API docs request

### ISSUE THREAD

**Issue by tcrowe** [dydxprotocol/solo#347]
Here there are two undocumented querystring options:
https://github.com/dydxprotocol/liquidator/blob/946ad0cc2ee17936d4beac1a0e15bace17f600c8/src/clients/dydx.js#L9
https://github.com/dydxprotocol/liquidator/blob/946ad0cc2ee17936d4beac1a0e15bace17f600c8/src/clients/dydx.js#L22

If you don't use those when requesting the accounts you get all accounts, which at the time of writing this, was around 14K. I'm not sure yet what other options exist but whatever querying options exist would be interesting to me.

Thank you, -TC

**Comment by BrendanChou** [comment]
These are both undocumented as they are subject to change. You can get all accounts for a particular address by supplying it e.g. https://api.dydx.exchange/v1/accounts/0x...

There is also the optional parameter `number` which can be provided to just get the particular account number for that address
