### ISSUE TITLE
Please publish the full source code of Solo Margin!

### ISSUE THREAD

**Issue by ytrezq** [dydxprotocol/solo#350]
The main function used for controlling token transfers (selector `0xa67a6a45`) doesn’t have it’s source code known (nor in GitHub nor on Etherscan).

If not having the full source known, would it be possible to have it least the code controlling token deposits and withdrawals open source?

**Comment by BrendanChou** [comment]
The full source code is in this repo and on Etherscan.

Link to requested function selector: https://github.com/dydxprotocol/solo/blob/master/contracts/protocol/Operation.sol#L54

Link to Etherscan with verified code:
https://etherscan.io/address/0x1e0447b19bb6ecfdae1e4ae1694b0c3659614e4e#code

**Comment by ytrezq** [comment]
Link to requested function selector: 
   https://github.com/dydxprotocol/solo/blob/master/contracts/protocol/Operation.sol#L54
@BrendanChou : Ok, I understand now why Etherscan fails to decode the function selector : the arguments used aren’t the same. Would it be possible to have the source code updated to reflect this ?

**Comment by BrendanChou** [comment]
What do you mean by "the arguments used aren't the same"?
