### ISSUE TITLE
No documentation about adding a custom ERC20 token for the public or a private fork of the protocol...

### ISSUE THREAD

**Issue by cleancoindev** [dydxprotocol/solo#413]
Hello, Thank you for all the great work you do.

I am curious how one would go about adding a token to the DYDX protocol that is up and coming for lending that will be backed by a pool of carbon credits and will be a stable-coin fiat token similar to the other lending protocols, forked from USDC project.

How would one go about working with the DYDX team to integrate this?  I have already worked on getting 0x relayers working with this and all is well with that, I am ready to integrate Compound, DYDX, and some of the other really good DeFi projects into this new fiat token, but If I cannot get the team's help then my question and issue is:

How do I set up a private fork of this protocol that does allow use and access to my stablefiat-pegged lending/borrowing token protocol?  {I use 0x so far.  working on Kyber integration as well}

**Comment by BrendanChou** [comment]
We're not currently accepting requests for new tokens on the existing protocol, but you're able to set up your own copy of any of these contracts if you want. You should check out the deployment scripts under the `migrations` folder.
