### ISSUE TITLE
Error: Returned error: The method eth_sign does not exist/is not available (on Infura)

### ISSUE THREAD

**Issue by dumebi** [dydxprotocol/solo#456]
According to solo documentation [here](https://docs.dydx.exchange/#/typescript), initialization can happen with infura
but when i make an order using the typescript place order [here](https://docs.dydx.exchange/#/typescript?id=place-orderv2), I get 
 `Error: Returned error: The method eth_sign does not exist/is not available`

**Comment by BrendanChou** [comment]
Your account must sign the order before sending to Infura (which does not hold a private key)
