### ISSUE TITLE
I accidentally sent a token to a token contract. Can I get it back?

### ISSUE THREAD

**Issue by m-yeganeh** [dydxprotocol/solo#511]
I accidentally sent it to the dydx contract itself.

https://etherscan.io/tx/0x7fc386c035d9c084f575889846f33cc59ef829576ba41cb09617aba4643f694f

Would you be able to send it back to me? 😭

**Comment by BrendanChou** [comment]
Like most other smart contracts, tokens sent directly to the contract are not recoverable. dYdX does not have the power to do that, but you could start a governance vote to modify the contract to send your funds back to you, though I would guess that's unlikely to pass. (BTW this looks like it's for the Layer-2 perpetual and not this repository, `solo`)
